SET(CMAKE_SYSTEM_NAME Windows)
SET(HOME "$ENV{HOME}")
SET(CMAKE_C_COMPILER "/opt/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-gcc")
SET(CMAKE_CXX_COMPILER "/opt/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-g++")
SET(CMAKE_RC_COMPILER "/opt/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-windres")
SET(CMAKE_FIND_ROOT_PATH "/opt/x86_64-w64-mingw32/x86_64-w64-mingw32/;${HOME}/mxe-shared/usr/x86_64-w64-mingw32.shared/")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_C_FLAGS_RELEASE "-D__1ENABLE_AGGRESSIVE_GRAPHITE9__ -funsafe-math-optimizations")
set(CMAKE_CXX_FLAGS_RELEASE "-D__1ENABLE_AGGRESSIVE_GRAPHITE9__ -funsafe-math-optimizations")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT "-Wl,-O3,--relax,--sort-section=alignment,--sort-common=descending")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE_INIT "-Wl,-O3,--relax,--sort-section=alignment,--sort-common=descending")
